/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_10 (
    input [5:0] alufn,
    input z,
    input v,
    input n,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] cmp
  );
  
  
  
  reg cmp1;
  
  reg [15:0] mul;
  
  reg [15:0] div;
  
  always @* begin
    
    case (alufn[0+2-:3])
      3'h2: begin
        cmp1 = a == b;
        cmp[1+14-:15] = 15'h0000;
        cmp[0+0-:1] = cmp1;
      end
      3'h4: begin
        cmp1 = a < b;
        cmp[1+14-:15] = 15'h0000;
        cmp[0+0-:1] = cmp1;
      end
      3'h6: begin
        cmp1 = a <= b;
        cmp[1+14-:15] = 15'h0000;
        cmp[0+0-:1] = cmp1;
      end
      3'h0: begin
        mul = a * b;
        cmp = mul[0+15-:16];
      end
      3'h7: begin
        div = a / b;
        cmp = div[0+15-:16];
      end
      default: begin
        cmp = 16'h0000;
      end
    endcase
  end
endmodule
