/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_5 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] alu,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [16-1:0] M_add_sum;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_n;
  reg [6-1:0] M_add_alufn;
  reg [16-1:0] M_add_a;
  reg [16-1:0] M_add_b;
  adder_9 add (
    .alufn(M_add_alufn),
    .a(M_add_a),
    .b(M_add_b),
    .sum(M_add_sum),
    .v(M_add_v),
    .z(M_add_z),
    .n(M_add_n)
  );
  
  wire [16-1:0] M_comp_cmp;
  reg [6-1:0] M_comp_alufn;
  reg [1-1:0] M_comp_z;
  reg [1-1:0] M_comp_v;
  reg [1-1:0] M_comp_n;
  reg [16-1:0] M_comp_a;
  reg [16-1:0] M_comp_b;
  compare_10 comp (
    .alufn(M_comp_alufn),
    .z(M_comp_z),
    .v(M_comp_v),
    .n(M_comp_n),
    .a(M_comp_a),
    .b(M_comp_b),
    .cmp(M_comp_cmp)
  );
  
  wire [16-1:0] M_boole_bool;
  reg [6-1:0] M_boole_alufn;
  reg [16-1:0] M_boole_a;
  reg [16-1:0] M_boole_b;
  boolean_11 boole (
    .alufn(M_boole_alufn),
    .a(M_boole_a),
    .b(M_boole_b),
    .bool(M_boole_bool)
  );
  
  wire [16-1:0] M_shift_shift;
  reg [16-1:0] M_shift_a;
  reg [16-1:0] M_shift_b;
  reg [6-1:0] M_shift_alufn;
  shifter_12 shift (
    .a(M_shift_a),
    .b(M_shift_b),
    .alufn(M_shift_alufn),
    .shift(M_shift_shift)
  );
  
  always @* begin
    M_add_a = a;
    M_add_b = b;
    M_add_alufn = alufn;
    M_comp_v = M_add_v;
    M_comp_n = M_add_n;
    M_comp_z = M_add_z;
    M_comp_a = a;
    M_comp_b = b;
    M_comp_alufn = alufn;
    M_boole_a = a;
    M_boole_b = b;
    M_boole_alufn = alufn;
    M_shift_a = a;
    M_shift_b = b;
    M_shift_alufn = alufn;
    
    case (alufn[4+1-:2])
      2'h0: begin
        alu = M_add_sum;
      end
      2'h1: begin
        alu = M_boole_bool;
      end
      2'h2: begin
        alu = M_shift_shift;
      end
      2'h3: begin
        alu = M_comp_cmp;
      end
      default: begin
        alu = 8'h00;
      end
    endcase
    z = M_add_z;
    v = M_add_v;
    n = M_add_n;
  end
endmodule
