/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module stateCounter_6 (
    input clk,
    input rst,
    output reg inc_state
  );
  
  
  
  reg [28:0] M_stateCounter_d, M_stateCounter_q = 1'h0;
  
  always @* begin
    M_stateCounter_d = M_stateCounter_q;
    
    inc_state = M_stateCounter_q[28+0-:1];
    M_stateCounter_d = M_stateCounter_q + 1'h1;
    if (M_stateCounter_q[28+0-:1] == 1'h1) begin
      M_stateCounter_d[28+0-:1] = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_stateCounter_q <= 1'h0;
    end else begin
      M_stateCounter_q <= M_stateCounter_d;
    end
  end
  
endmodule
